apiVersion: compute.crossplane.io/v1alpha1
kind: KubernetesCluster
metadata:
  name: demo-gke-cluster
  namespace: crossplane-system
spec:
  classReference:
    name: standard-cluster
    namespace: crossplane-system
