## GCP Service Account Credentials
apiVersion: v1
data:
  credentials.json: BASE64ENCODED_CREDS
kind: Secret
metadata:
  namespace: crossplane-system
  name: gcp-provider-creds
type: Opaque
---
## Crossplane GCP Provider
apiVersion: gcp.crossplane.io/v1alpha1
kind: Provider
metadata:
  namespace: crossplane-system
  name: gcp-provider
spec:
  credentialsSecretRef:
    name: gcp-provider-creds
    key: credentials.json
  projectID: PROJECT_ID
---
## Crossplane Kubernetes Cluster Resource Class for GCP
apiVersion: core.crossplane.io/v1alpha1
kind: ResourceClass
metadata:
  name: standard-cluster
  namespace: crossplane-system
parameters:
  machineType: n1-standard-1
  numNodes: "1"
  zone: southamerica-east1-a
provisioner: gkecluster.compute.gcp.crossplane.io/v1alpha1
providerRef:
  name: gcp-provider
reclaimPolicy: Delete
---
## Crossplane MySQL Resource Class for GCP (CloudSQL)
apiVersion: core.crossplane.io/v1alpha1
kind: ResourceClass
metadata:
  name: standard-mysql
  namespace: crossplane-system
parameters:
  tier: db-n1-standard-1
  region: southamerica-east1
  storageType: PD_SSD
provisioner: cloudsqlinstance.database.gcp.crossplane.io/v1alpha1
providerRef:
  name: gcp-provider
reclaimPolicy: Delete
